name: Terraform Lint and Validate

on:
  push:
    branches:
      - master

jobs:
  terraform-lint:
    name: Lint and Validate All Terraform Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Find and Validate Terraform Directories
        run: |
          for dir in $(find . -type f -name "*.tf" -exec dirname {} \; | sort -u); do
            echo "Processing directory: $dir"
            cd "$dir"
            
            terraform init -backend=false
            terraform fmt -check -recursive
            terraform validate
            cd - > /dev/null
          done